### PR TITLE
added simple cmake build file

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Comment by junghans** [comment]
Just FYI, this is basically that we can implement the `DOWNLOAD_MSCG` in LAMMPS' cmake build system easier! We could use one of the Makefiles, but that makes it very tricky to use LAMMPS' lapack replacement.

**Comment by tdlafage** [comment]
Hello Christoph,

I am sure that this is fine. I am just going to test it first. The one recommendation I would suggest is putting authorship on the top of the file. 

Best,
Thomas

**Comment by tdlafage** [comment]
Hello Christoph,

It looks like this does what you intended. The only thing we would ask you to do before we merge the pull request is to add to the README_lammps.txt file something that explains the usage of the cmake file and which step it is meant to replace/augment. 

Thanks in advance.

Best,
Thomas

**Comment by junghans** [comment]
As we haven't officially announced the CMake build system for LAMMPS, so I wouldn't put anything in `README_lammps.txt` yet. But the intended use with LAMMPS CMake build system is to just run:
```
cmake -DPKG_MSCG=ON -DDOWNLOAD_MSCG=ON ../cmake
```
(in same way as we have implemented it for the `VORO`, `LATTE` and `KIM` package).
And the `CMakeLists.txt` from this PR will be use by CMake.

**Comment by tdlafage** [comment]
Thank you for the last commit. merging now.

**Pull request merged**
